Issue/45 docker
ucfopen/quiz-extensions pull request #46
Opened 2021-09-03 16:52 UTC by ssilverm

# Proposed Changes

This Dockerizes Quiz Extensions.

2021-10-19 16:50 UTC, Thetwam requested changes
Need to add `FLASK_APP` and `FLASK_DEBUG` environment variables

Tests fail because the template for config.py is missing. Need to update `run-tests.yml` to support the new setup.

I noticed HTTPS isn't supported. I would like to retain that functionality.

2021-11-02 14:53 UTC, Thetwam commented
Need to pull in latest `develop`, address conflicts, and address comments above.

2021-11-04 16:30 UTC, ssilverm commented on README.md
> +    db.create_all()
Fixed.

2021-11-04 16:31 UTC, ssilverm commented on docker-compose.production.yaml
> +#   quizext_db_data: {}
Removed these lines and added a comment about what is still needed in production.

2021-11-04 16:31 UTC, ssilverm commented on config.py
> -        },
Because docker outputs everything to stdout which can then be piped wherever...

2026-04-10 14:53 UTC, Thetwam commented
Closing in favor of #70

2026-04-10 14:53 UTC, closed without merging